// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7DMC1TB1Uzc-XmMN4KSNPbKRXd9Pgdxs',
    appId: '1:178459381037:web:9318c66b17cdbbb69f17a4',
    messagingSenderId: '178459381037',
    projectId: 'zelda-fly',
    authDomain: 'zelda-fly.firebaseapp.com',
    storageBucket: 'zelda-fly.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkCCypws0tqMJtX9gbZNd3LdA2W2IYWcg',
    appId: '1:178459381037:android:bda66d207bb48dfd9f17a4',
    messagingSenderId: '178459381037',
    projectId: 'zelda-fly',
    storageBucket: 'zelda-fly.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuw_iVzPayvz9WhpiW24avOny22ktUQhs',
    appId: '1:178459381037:ios:da8f58a390cce9179f17a4',
    messagingSenderId: '178459381037',
    projectId: 'zelda-fly',
    storageBucket: 'zelda-fly.appspot.com',
    iosBundleId: 'com.zeldafly.zeldafly',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDuw_iVzPayvz9WhpiW24avOny22ktUQhs',
    appId: '1:178459381037:ios:da8f58a390cce9179f17a4',
    messagingSenderId: '178459381037',
    projectId: 'zelda-fly',
    storageBucket: 'zelda-fly.appspot.com',
    iosBundleId: 'com.zeldafly.zeldafly',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB7DMC1TB1Uzc-XmMN4KSNPbKRXd9Pgdxs',
    appId: '1:178459381037:web:552a548e621160e89f17a4',
    messagingSenderId: '178459381037',
    projectId: 'zelda-fly',
    authDomain: 'zelda-fly.firebaseapp.com',
    storageBucket: 'zelda-fly.appspot.com',
  );
}
